### ISSUE TITLE
No MySql in the end to end

### ISSUE THREAD

**Issue by nargov** [jgstr/twitchwebsub#1]
https://github.com/jgstr/twitchwebsub/blob/1c6d454795ffd837782448b37fc7f61012c36436/end-to-end/e2e-test.js#L35-L52

This doesn't belong here. It belongs in the server.
The test should operate the system as any other user would.
In this case through a web interface.

**Comment by jgstr** [comment]
MySQL/database features are now in the subscriber-server.js module.
