### ISSUE TITLE
Promise.resolve()

### ISSUE THREAD

**Issue by nargov** [jgstr/twitchwebsub#11]
https://github.com/jgstr/twitchwebsub/blob/5dc1ac46ce64279f741ec02edf021ec95998d901/subscriber/doubles/twitch-stub.js#L2

Replace with `Promise.resolve(...)`

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/resolve

**Comment by jgstr** [comment]
Done.
