### ISSUE TITLE
Long parameter list

### ISSUE THREAD

**Issue by nargov** [jgstr/twitchwebsub#15]
https://github.com/jgstr/twitchwebsub/blob/5dc1ac46ce64279f741ec02edf021ec95998d901/subscriber/subscriber-server.js#L4

The parameter list to this create function is getting quite long.
This usually means one (or more) of the following:
1. Some of the parameters are related to each other, and can be put in some object and passed as a single parameter.
2. This create function is doing too many things, and there needs to be a new collaborator that gets passed in instead.

**Comment by jgstr** [comment]
Solution [currently in progress](https://github.com/jgstr/twitchwebsub/tree/wiring-refactor).

**Comment by jgstr** [comment]
Resolved with the [wiring-refactor](https://github.com/jgstr/twitchwebsub/tree/wiring-refactor) branch.
