### ISSUE TITLE
Do it

### ISSUE THREAD

**Issue by nargov** [jgstr/twitchwebsub#16]
https://github.com/jgstr/twitchwebsub/blob/5dc1ac46ce64279f741ec02edf021ec95998d901/tests/data-store-integration-test.js#L92

**Comment by jgstr** [comment]
Geez that ended up being more complicated than I thought. But at least I have a crude version passing: [https://github.com/jgstr/twitchwebsub/commit/f78befa978827c088b9080adc3770a0956316af4](url)
