### ISSUE TITLE
Too complicated?

### ISSUE THREAD

**Issue by nargov** [jgstr/twitchwebsub#2]
https://github.com/jgstr/twitchwebsub/blob/bf911dee39bfcf1decdad8c76f047bf7233c7365/end-to-end/e2e-test.js#L51

Why is this needed? You have an instance of the fake twitch at your finger tips.
You can just use a function to tell it to do stuff if you want to.

**Comment by jgstr** [comment]
fake-twitch now implements methods that the end-to-end test can call directly.
