### ISSUE TITLE
Missing Twitch Adapter

### ISSUE THREAD

**Issue by nargov** [jgstr/twitchwebsub#4]
https://github.com/jgstr/twitchwebsub/blob/a5ac71bf651c8432e0282a1d611882e7188195f5/tests/subscriber-tests.js#L17

The problem you're having is that your code uses the implementation and not an abstraction.
Remember ports and adapters? The internet (and specifically twitch) is a port.
If you add an adapter to twitch, the rest of your code will use the adapter, and have no idea _how_ twitch is actually contacted.
Adapters are tested using integration tests (using the fake twitch, and maybe a contract test).
The usage of the adapter can be tested with unit tests.

**Comment by jgstr** [comment]
Created twitch adapter.
