### ISSUE TITLE
Primary Key should be composition

### ISSUE THREAD

**Issue by nargov** [jgstr/twitchwebsub#7]
https://github.com/jgstr/twitchwebsub/blob/5dc1ac46ce64279f741ec02edf021ec95998d901/database/sql-scripts/create-table.sql#L15

Since most likely you'll be searching for events for a given subscription, and not just events on their own, the primary key should be (subscription_id, id).
Another option can be to leave the primary key as it is, and add an index on (subscription_id, id).
Read about indexes in MySQL.

**Comment by jgstr** [comment]
Primary Key for Events is now a composite of the `subscription_id` and event `id`.
[https://github.com/jgstr/twitchwebsub/commit/2851238863678d98dad16734db2408776e5939e9](url)
